### ISSUE TITLE
Recognize changes in url

### ISSUE THREAD

**Issue by GrantRynders** [GrantRynders/Github-Extension-Project#44]

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###
