### ISSUE TITLE
Calculate total time spent on an issue, and append it to the lgo

### ISSUE THREAD

**Issue by GrantRynders** [GrantRynders/Github-Extension-Project#45]

**Comment by deshyah** [comment]
###deshyahTimeLog###

**Comment by deshyah** [comment]
###deshyahTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by ScarfKid188** [comment]
###ScarfKid188TimeLog###

**Comment by ScarfKid188** [comment]
###ScarfKid188TimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###
. . . . 
start date: Fri Jun 21 2024 09:55:01 GMT-0400 (Eastern Daylight Time)
timer start value: 00:00:00:01
. . . .
stop date: Fri Jun 21 2024 09:55:09 GMT-0400 (Eastern Daylight Time)
timer stop value: 00:00:00:08
. . . .
Total Time Spent So Far: 00:00:00:08
. . . . 
start date: Fri Jun 21 2024 09:55:13 GMT-0400 (Eastern Daylight Time)
timer start value: 00:00:00:09
. . . .
stop date: Fri Jun 21 2024 09:55:19 GMT-0400 (Eastern Daylight Time)
timer stop value: 00:00:00:13
. . . .
Total Time Spent So Far: 00:00:00:14
